/**
 * @file main.c
 * @brief Application entry point. Boots CAN + UART, then runs a simple
 *        1ms cooperative scheduler that:
 *          - drains any pending CAN diagnostic frame -> Diag_HandleCanFrame
 *          - drains any complete UART console line   -> Diag_HandleConsoleLine
 *          - ticks the fault simulator every FAULT_SIM_PERIOD_MS
 *          - ticks the diagnostic session timeout every ms
 *
 * Peripheral handles (hcan1, huart1, etc.) and their low-level Init
 * (GPIO/clock/timing config) are expected to come from CubeMX-generated
 * MX_CAN1_Init()/MX_USART1_UART_Init() — only application wiring lives here.
 */
#include "main.h"
#include "can_driver.h"
#include "uart_driver.h"
#include "diagnostics.h"

/* Peripheral handles — the interrupt handlers in stm32f1xx_it.c reference
 * these via extern too, so HAL_CAN_IRQHandler()/HAL_UART_IRQHandler() can
 * find the right instance. */
CAN_HandleTypeDef  hcan1;
UART_HandleTypeDef huart1;

void SystemClock_Config(void);
static void MX_GPIO_Init(void);
static void MX_CAN1_Init(void);
static void MX_USART1_UART_Init(void);

static uint32_t s_fault_sim_accum_ms = 0U;

int main(void)
{
    HAL_Init();
    SystemClock_Config();

    MX_GPIO_Init();
    MX_CAN1_Init();
    MX_USART1_UART_Init();

    if (Can_Driver_Init(&hcan1) != CAN_OK) {
        Error_Handler();
    }
    if (Uart_Driver_Init(&huart1) != UART_OK) {
        Error_Handler();
    }
    Diag_Init();

    Uart_Driver_SendString(
        "\r\n=== Automotive ECU Comm & Diagnostics System ===\r\n"
        "Type 'help' for console commands.\r\n> ");

    char line[UART_LINE_MAX_LEN];
    CanFrame_t can_frame;

    while (1) {
        /* --- CAN diagnostic requests -------------------------------- */
        while (Can_Driver_Available()) {
            if (Can_Driver_Receive(&can_frame) == CAN_OK) {
                Diag_HandleCanFrame(&can_frame);
            }
        }

        /* --- UART console commands ------------------------------------ */
        if (Uart_Driver_ReadLine(line, sizeof(line))) {
            Diag_HandleConsoleLine(line);
            Uart_Driver_SendString("> ");
        }

        /* --- periodic housekeeping -------------------------------------
         * A free-running HAL_Delay(1) keeps this a simple, readable
         * cooperative loop. Swap for a SysTick-driven flag / RTOS task if
         * you need the CPU free for other work between iterations. */
        HAL_Delay(SYSTEM_TICK_MS);
        Diag_SessionTick(SYSTEM_TICK_MS);

        s_fault_sim_accum_ms += SYSTEM_TICK_MS;
        if (s_fault_sim_accum_ms >= FAULT_SIM_PERIOD_MS) {
            s_fault_sim_accum_ms = 0U;
            Diag_FaultSimulatorTick();
        }
    }
}

void Error_Handler(void)
{
    __disable_irq();
    while (1) {
        /* Toggle status LED fast so a hang is visibly distinguishable from
         * normal operation on the bench. */
        HAL_GPIO_TogglePin(STATUS_LED_GPIO_Port, STATUS_LED_Pin);
        for (volatile uint32_t i = 0; i < 200000U; i++) { }
    }
}

/* ==========================================================================
 * HAL callback glue — forwards into the small drivers above. Real projects
 * generated by CubeIDE put these in stm32*_it.c; kept here for a
 * single-file-per-concern layout in this standalone repo.
 * ========================================================================*/
void HAL_CAN_RxFifo0MsgPendingCallback(CAN_HandleTypeDef *hcan)
{
    Can_Driver_RxCallback(hcan);
}

void HAL_UART_RxCpltCallback(UART_HandleTypeDef *huart)
{
    Uart_Driver_RxCallback(huart);
}

/* ==========================================================================
 * SystemClock_Config — Blue Pill reference clock tree:
 *   HSE (8MHz crystal) -> PLL x9 -> SYSCLK 72MHz
 *   AHB = 72MHz, APB1 = 36MHz (bxCAN timing below assumes this), APB2 = 72MHz
 * ========================================================================*/
void SystemClock_Config(void)
{
    RCC_OscInitTypeDef osc = {0};
    RCC_ClkInitTypeDef clk = {0};

    osc.OscillatorType = RCC_OSCILLATORTYPE_HSE;
    osc.HSEState       = RCC_HSE_ON;
    osc.HSEPredivValue = RCC_HSE_PREDIV_DIV1;
    osc.PLL.PLLState   = RCC_PLL_ON;
    osc.PLL.PLLSource  = RCC_PLLSOURCE_HSE;
    osc.PLL.PLLMUL     = RCC_PLL_MUL9;      /* 8MHz * 9 = 72MHz */
    if (HAL_RCC_OscConfig(&osc) != HAL_OK) {
        Error_Handler();
    }

    clk.ClockType      = RCC_CLOCKTYPE_SYSCLK | RCC_CLOCKTYPE_HCLK |
                          RCC_CLOCKTYPE_PCLK1 | RCC_CLOCKTYPE_PCLK2;
    clk.SYSCLKSource   = RCC_SYSCLKSOURCE_PLLCLK;
    clk.AHBCLKDivider  = RCC_SYSCLK_DIV1;   /* HCLK  = 72MHz */
    clk.APB1CLKDivider = RCC_HCLK_DIV2;     /* PCLK1 = 36MHz (APB1 max) */
    clk.APB2CLKDivider = RCC_HCLK_DIV1;     /* PCLK2 = 72MHz */
    if (HAL_RCC_ClockConfig(&clk, FLASH_LATENCY_2) != HAL_OK) {
        Error_Handler();
    }
}

/* ==========================================================================
 * GPIO — status LED (PC13), CAN1 (PA11/PA12, default mapping, no AFIO
 * remap needed), USART1 (PA9 TX / PA10 RX, default mapping).
 * ========================================================================*/
static void MX_GPIO_Init(void)
{
    __HAL_RCC_GPIOA_CLK_ENABLE();
    __HAL_RCC_GPIOC_CLK_ENABLE();
    __HAL_RCC_AFIO_CLK_ENABLE();

    GPIO_InitTypeDef gpio = {0};

    /* Status LED — push-pull output */
    gpio.Pin   = STATUS_LED_Pin;
    gpio.Mode  = GPIO_MODE_OUTPUT_PP;
    gpio.Pull  = GPIO_NOPULL;
    gpio.Speed = GPIO_SPEED_FREQ_LOW;
    HAL_GPIO_Init(STATUS_LED_GPIO_Port, &gpio);

    /* CAN1 TX (PA12) — AF push-pull */
    gpio.Pin   = CAN_TX_Pin;
    gpio.Mode  = GPIO_MODE_AF_PP;
    gpio.Pull  = GPIO_NOPULL;
    gpio.Speed = GPIO_SPEED_FREQ_HIGH;
    HAL_GPIO_Init(CAN_TX_GPIO_Port, &gpio);

    /* CAN1 RX (PA11) — input with pull-up (idle-high recessive bus) */
    gpio.Pin  = CAN_RX_Pin;
    gpio.Mode = GPIO_MODE_INPUT;
    gpio.Pull = GPIO_PULLUP;
    HAL_GPIO_Init(CAN_RX_GPIO_Port, &gpio);

    /* USART1 TX (PA9) — AF push-pull */
    gpio.Pin   = GPIO_PIN_9;
    gpio.Mode  = GPIO_MODE_AF_PP;
    gpio.Pull  = GPIO_NOPULL;
    gpio.Speed = GPIO_SPEED_FREQ_HIGH;
    HAL_GPIO_Init(GPIOA, &gpio);

    /* USART1 RX (PA10) — floating input */
    gpio.Pin  = GPIO_PIN_10;
    gpio.Mode = GPIO_MODE_INPUT;
    gpio.Pull = GPIO_NOPULL;
    HAL_GPIO_Init(GPIOA, &gpio);
}

/* ==========================================================================
 * CAN1 — 500 kbps on a 36MHz APB1 clock:
 *   Prescaler=4, BS1=9TQ, BS2=8TQ, SJW=1TQ  ->  1 + 9 + 8 = 18 TQ/bit
 *   bit time = 18 * (4 / 36MHz) = 2.0us = 500kHz, sample point ~55.6%
 * ========================================================================*/
static void MX_CAN1_Init(void)
{
    __HAL_RCC_CAN1_CLK_ENABLE();

    hcan1.Instance = CAN1;
    hcan1.Init.Prescaler          = 4;
    hcan1.Init.Mode                = CAN_MODE_NORMAL;
    hcan1.Init.SyncJumpWidth       = CAN_SJW_1TQ;
    hcan1.Init.TimeSeg1            = CAN_BS1_9TQ;
    hcan1.Init.TimeSeg2            = CAN_BS2_8TQ;
    hcan1.Init.TimeTriggeredMode   = DISABLE;
    hcan1.Init.AutoBusOff          = ENABLE;
    hcan1.Init.AutoWakeUp          = DISABLE;
    hcan1.Init.AutoRetransmission  = ENABLE;
    hcan1.Init.ReceiveFifoLocked   = DISABLE;
    hcan1.Init.TransmitFifoPriority = DISABLE;

    if (HAL_CAN_Init(&hcan1) != HAL_OK) {
        Error_Handler();
    }

    HAL_NVIC_SetPriority(USB_LP_CAN1_RX0_IRQn, 1, 0);
    HAL_NVIC_EnableIRQ(USB_LP_CAN1_RX0_IRQn);
}

/* ==========================================================================
 * USART1 — 115200 8N1, interrupt-driven RX (single byte at a time, see
 * uart_driver.c), polling TX (console output is small/infrequent).
 * ========================================================================*/
static void MX_USART1_UART_Init(void)
{
    __HAL_RCC_USART1_CLK_ENABLE();

    huart1.Instance          = USART1;
    huart1.Init.BaudRate     = 115200;
    huart1.Init.WordLength   = UART_WORDLENGTH_8B;
    huart1.Init.StopBits     = UART_STOPBITS_1;
    huart1.Init.Parity       = UART_PARITY_NONE;
    huart1.Init.Mode         = UART_MODE_TX_RX;
    huart1.Init.HwFlowCtl    = UART_HWCONTROL_NONE;
    huart1.Init.OverSampling = UART_OVERSAMPLING_16;

    if (HAL_UART_Init(&huart1) != HAL_OK) {
        Error_Handler();
    }

    HAL_NVIC_SetPriority(USART1_IRQn, 2, 0);
    HAL_NVIC_EnableIRQ(USART1_IRQn);
}
